- 👋 Hi, I’m @habdulmlik
- 👀 I am an expert blockchain developer working with an expert team with over 4 years of expereince in creating any website any blockchain like solana , polygon, binance smart chain, cardano, matic and mamy more and also have a good expereince in token creation and depolyment and provide full ownership with source code
- 📫 How to reach me ... you can message me on telegram @newclassic0 or fiverr.com/habeebllah01 
